"""Mock lead data for IT Infrastructure Lead Generator."""

LEADS = [
    {
        "id": 1,
        "company": "Meridian Financial Group",
        "industry": "Finance",
        "size": "500-1000",
        "location": "New York, NY",
        "it_type": "Hybrid",
        "contact_name": "James Thornton",
        "contact_title": "CTO",
        "contact_email": "j.thornton@meridianfg.com",
        "contact_phone": "+1 (212) 555-0147",
        "current_infra": "On-prem servers aging out, partial Azure migration",
        "pain_points": ["Legacy hardware maintenance costs", "DR/backup gaps", "Compliance (SOX)"],
        "annual_it_budget": "$4.2M",
        "employees": 720,
        "website": "meridianfg.com",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 2,
        "company": "Crestview Healthcare Systems",
        "industry": "Healthcare",
        "size": "1000-5000",
        "location": "Chicago, IL",
        "it_type": "On-Premise",
        "contact_name": "Dr. Sandra Koh",
        "contact_title": "VP of IT",
        "contact_email": "s.koh@crestviewhealth.org",
        "contact_phone": "+1 (312) 555-0283",
        "current_infra": "Aging VMware environment, no cloud footprint",
        "pain_points": ["HIPAA compliance burden", "Uptime requirements (99.99%)", "EHR system latency"],
        "annual_it_budget": "$11.5M",
        "employees": 2400,
        "website": "crestviewhealth.org",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 3,
        "company": "Pinnacle Logistics Co.",
        "industry": "Logistics",
        "size": "200-500",
        "location": "Dallas, TX",
        "it_type": "Cloud",
        "contact_name": "Marcus Ellis",
        "contact_title": "IT Director",
        "contact_email": "m.ellis@pinnaclelogistics.com",
        "contact_phone": "+1 (469) 555-0391",
        "current_infra": "AWS-heavy, single cloud, no MSP relationship",
        "pain_points": ["Cloud cost overruns", "No 24/7 support", "Security posture gaps"],
        "annual_it_budget": "$1.8M",
        "employees": 340,
        "website": "pinnaclelogistics.com",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 4,
        "company": "Redwood Manufacturing Inc.",
        "industry": "Manufacturing",
        "size": "500-1000",
        "location": "Detroit, MI",
        "it_type": "On-Premise",
        "contact_name": "Linda Vasquez",
        "contact_title": "Head of Infrastructure",
        "contact_email": "l.vasquez@redwoodmfg.com",
        "contact_phone": "+1 (313) 555-0512",
        "current_infra": "Physical servers, no virtualization, running EOL Windows Server 2012",
        "pain_points": ["EOL OS risk", "No disaster recovery", "OT/IT convergence challenges"],
        "annual_it_budget": "$2.9M",
        "employees": 870,
        "website": "redwoodmfg.com",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 5,
        "company": "Atlas Education Group",
        "industry": "Education",
        "size": "200-500",
        "location": "Boston, MA",
        "it_type": "Cloud",
        "contact_name": "Tom Nguyen",
        "contact_title": "CIO",
        "contact_email": "t.nguyen@atlasedu.org",
        "contact_phone": "+1 (617) 555-0678",
        "current_infra": "Google Workspace + Azure AD, no unified security layer",
        "pain_points": ["Student data privacy (FERPA)", "Ransomware exposure", "Budget constraints"],
        "annual_it_budget": "$900K",
        "employees": 280,
        "website": "atlasedu.org",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 6,
        "company": "Summit Retail Partners",
        "industry": "Retail",
        "size": "1000-5000",
        "location": "Atlanta, GA",
        "it_type": "Hybrid",
        "contact_name": "Rachel Moore",
        "contact_title": "VP Technology",
        "contact_email": "r.moore@summitretail.com",
        "contact_phone": "+1 (404) 555-0734",
        "current_infra": "Mixed AWS + on-prem POS systems, 80 locations",
        "pain_points": ["PCI-DSS compliance across locations", "Network latency at stores", "Centralized IT visibility"],
        "annual_it_budget": "$8.3M",
        "employees": 3100,
        "website": "summitretail.com",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 7,
        "company": "Keystone Legal LLP",
        "industry": "Legal",
        "size": "100-200",
        "location": "San Francisco, CA",
        "it_type": "On-Premise",
        "contact_name": "David Park",
        "contact_title": "IT Manager",
        "contact_email": "d.park@keystonelegal.com",
        "contact_phone": "+1 (415) 555-0845",
        "current_infra": "Local file servers, no cloud backup, single IT staff",
        "pain_points": ["Data loss risk", "No IT redundancy", "Client confidentiality compliance"],
        "annual_it_budget": "$450K",
        "employees": 130,
        "website": "keystonelegal.com",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 8,
        "company": "Orion Energy Solutions",
        "industry": "Energy",
        "size": "500-1000",
        "location": "Houston, TX",
        "it_type": "Hybrid",
        "contact_name": "Brian Cole",
        "contact_title": "CTO",
        "contact_email": "b.cole@orionenergy.com",
        "contact_phone": "+1 (713) 555-0962",
        "current_infra": "Azure + on-prem SCADA systems, minimal cybersecurity stack",
        "pain_points": ["OT security gaps", "Regulatory compliance (NERC CIP)", "Cloud expansion needs"],
        "annual_it_budget": "$5.7M",
        "employees": 610,
        "website": "orionenergy.com",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 9,
        "company": "Bright Minds EdTech",
        "industry": "Technology",
        "size": "50-200",
        "location": "Austin, TX",
        "it_type": "Cloud",
        "contact_name": "Priya Shah",
        "contact_title": "Head of Engineering",
        "contact_email": "p.shah@brightminds.io",
        "contact_phone": "+1 (512) 555-1023",
        "current_infra": "Multi-cloud (AWS + GCP), fast-growing, no managed security",
        "pain_points": ["Scaling infrastructure quickly", "DevSecOps gaps", "Cost visibility across clouds"],
        "annual_it_budget": "$700K",
        "employees": 95,
        "website": "brightminds.io",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 10,
        "company": "National Property Trust",
        "industry": "Real Estate",
        "size": "200-500",
        "location": "Phoenix, AZ",
        "it_type": "Hybrid",
        "contact_name": "Kevin Walsh",
        "contact_title": "Director of IT",
        "contact_email": "k.walsh@nationalproperty.com",
        "contact_phone": "+1 (602) 555-1134",
        "current_infra": "Microsoft 365 + aging on-prem, no MDM solution",
        "pain_points": ["Remote workforce security", "No endpoint management", "Vendor sprawl"],
        "annual_it_budget": "$1.2M",
        "employees": 260,
        "website": "nationalproperty.com",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 11,
        "company": "Vantage Insurance Group",
        "industry": "Insurance",
        "size": "1000-5000",
        "location": "Hartford, CT",
        "it_type": "On-Premise",
        "contact_name": "Angela Torres",
        "contact_title": "SVP Information Technology",
        "contact_email": "a.torres@vantageinsurance.com",
        "contact_phone": "+1 (860) 555-1247",
        "current_infra": "Legacy mainframe + Windows servers, cloud strategy in evaluation",
        "pain_points": ["Mainframe migration complexity", "Cyber insurance requirements", "Speed of IT delivery"],
        "annual_it_budget": "$14.2M",
        "employees": 1800,
        "website": "vantageinsurance.com",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
    {
        "id": 12,
        "company": "Clearwater Biotech",
        "industry": "Biotech",
        "size": "200-500",
        "location": "San Diego, CA",
        "it_type": "Cloud",
        "contact_name": "Dr. Nina Petrov",
        "contact_title": "VP IT & Data",
        "contact_email": "n.petrov@clearwaterbio.com",
        "contact_phone": "+1 (858) 555-1358",
        "current_infra": "AWS HPC clusters for R&D, minimal enterprise IT",
        "pain_points": ["FDA 21 CFR Part 11 compliance", "Data integrity for trials", "IT/Research alignment"],
        "annual_it_budget": "$3.1M",
        "employees": 320,
        "website": "clearwaterbio.com",
        "status": "Prospect",
        "notes": "",
        "last_contacted": None,
        "follow_up": None,
    },
]

INDUSTRIES = sorted(list(set(l["industry"] for l in LEADS)))
SIZES = ["50-200", "100-200", "200-500", "500-1000", "1000-5000"]
IT_TYPES = ["Cloud", "On-Premise", "Hybrid"]
LOCATIONS = sorted(list(set(l["location"].split(", ")[1] for l in LEADS)))

CALL_STATUSES = ["Prospect", "Contacted", "Voicemail", "Follow-up Scheduled", "Qualified", "Not Interested", "Closed Won"]

SCRIPT_TEMPLATES = {
    "Cloud": {
        "hook": "I noticed {company} has been scaling your cloud infrastructure — managing costs and security across multiple cloud platforms is one of the biggest challenges we hear from {industry} companies right now.",
        "pain": "A lot of {industry} IT leaders we speak with are dealing with {pain_1} and {pain_2} — does that resonate with what you're seeing?",
        "value": "CES helps companies like yours take back control — we provide managed cloud infrastructure, 24/7 monitoring, and a dedicated team that acts as an extension of your IT department, so your team can focus on the business.",
        "objection": "I completely understand — most of our clients had an internal team before working with us. What we typically do is a no-obligation infrastructure audit to show you exactly where the gaps are. It takes about 30 minutes and you keep the report regardless.",
        "cta": "Could we set up a 20-minute call this week or next to walk through what that looks like for {company}?",
    },
    "On-Premise": {
        "hook": "I'm reaching out because we work with a lot of {industry} companies that are running on-premise infrastructure — and we're seeing a real spike in demand for modernization, especially with EOL hardware and rising maintenance costs.",
        "pain": "Are you finding that keeping older systems running is eating into budget that could go toward growth? Things like {pain_1} and {pain_2} tend to come up a lot.",
        "value": "CES specializes in IT infrastructure transformation — from assessment through to migration and managed support. We've helped similar organizations cut infrastructure costs by 20-35% while improving uptime and compliance posture.",
        "objection": "Totally fair — we're not asking for a commitment. What we offer first is a complimentary infrastructure health check. It gives you a clear picture of your risk exposure and a roadmap you can act on at your own pace.",
        "cta": "Would {contact_name} have 20 minutes this week for a quick call? I can walk you through how we've helped similar {industry} organizations.",
    },
    "Hybrid": {
        "hook": "Hi {contact_name}, I'm calling from CES — we specialize in IT infrastructure for {industry} companies. I saw that {company} is running a hybrid environment, and managing consistency across cloud and on-prem is something a lot of our clients struggle with.",
        "pain": "Are challenges like {pain_1} or {pain_2} something that's on your radar right now?",
        "value": "We help hybrid environment teams get unified visibility, consistent security policies, and managed support across both worlds — without the overhead of building that capability in-house.",
        "objection": "I hear you — the last thing you need is another vendor conversation. What if we skipped the sales pitch and just did a complimentary architecture review? You'd get a plain-English summary of your risk areas and quick wins. No strings attached.",
        "cta": "Does Thursday or Friday work for a 20-minute call? I'll send a calendar invite right after.",
    },
}
