import { useMemo, useState } from 'react'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Modal } from '@/components/ui/Modal'
import { Badge } from '@/components/ui/Badge'
import {
  usePainPointCatalog,
  useCreatePainPoint,
  useUpdatePainPoint,
  useDeletePainPoint,
  type PainPointCatalogItem,
} from '@/hooks/usePainPointCatalog'
import { Plus, Pencil, Trash2, AlertCircle } from 'lucide-react'

const THEMES = ['Cloud', 'Security', 'Data', 'Infrastructure', 'AI', 'Operations', 'Talent', 'General']

function parseTags(raw: string): string[] {
  return raw
    .split(',')
    .map((t) => t.trim())
    .filter(Boolean)
}

export function PainPointsCatalogPage() {
  const { data: items = [], isLoading, error } = usePainPointCatalog()
  const createItem = useCreatePainPoint()
  const updateItem = useUpdatePainPoint()
  const deleteItem = useDeletePainPoint()

  const [search, setSearch] = useState('')
  const [themeFilter, setThemeFilter] = useState('')
  const [modalOpen, setModalOpen] = useState(false)
  const [editing, setEditing] = useState<PainPointCatalogItem | null>(null)
  const [form, setForm] = useState({ text: '', theme: 'General', tags: '' })

  const filtered = useMemo(() => {
    const q = search.toLowerCase()
    return items.filter((item) => {
      if (themeFilter && item.theme !== themeFilter) return false
      if (q && !item.text.toLowerCase().includes(q) && !item.tags.some((t) => t.toLowerCase().includes(q)))
        return false
      return true
    })
  }, [items, search, themeFilter])

  const openCreate = () => {
    setEditing(null)
    setForm({ text: '', theme: 'General', tags: '' })
    setModalOpen(true)
  }

  const openEdit = (item: PainPointCatalogItem) => {
    setEditing(item)
    setForm({ text: item.text, theme: item.theme, tags: item.tags.join(', ') })
    setModalOpen(true)
  }

  const handleSave = async () => {
    const payload = {
      text: form.text.trim(),
      theme: form.theme,
      tags: parseTags(form.tags),
      active: true,
    }
    if (!payload.text) return

    if (editing) {
      await updateItem.mutateAsync({ id: editing.id, ...payload })
    } else {
      await createItem.mutateAsync(payload)
    }
    setModalOpen(false)
  }

  const handleDelete = async (id: number) => {
    if (!confirm('Are you sure you want to remove this pain point from the catalog?')) return
    await deleteItem.mutateAsync(id)
  }

  if (isLoading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-ces-orange border-t-transparent" />
      </div>
    )
  }

  const tableMissing = error instanceof Error && error.message?.includes('does not exist')

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">Pain Points Catalog</h1>
          <p className="text-ces-muted">
            Manage a reusable library of pain points for script generation and intelligence.
          </p>
        </div>
        <Button variant="primary" onClick={openCreate}>
          <Plus className="h-4 w-4" /> Add Pain Point
        </Button>
      </div>

      {tableMissing && (
        <div className="flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
          <div>
            <p className="font-medium">Catalog table not found</p>
            <p className="mt-1">
              Run this SQL in the Supabase SQL Editor to enable the catalog:
            </p>
            <pre className="mt-2 overflow-x-auto rounded bg-amber-100 p-2 text-xs">
{`create table if not exists public.pain_point_catalog (
  id bigint generated by default as identity primary key,
  text text not null,
  theme text not null default 'General',
  tags text[] default array[]::text[],
  active boolean not null default true,
  created_at timestamp with time zone default now()
);

alter table public.pain_point_catalog enable row level security;

create policy "Allow all" on public.pain_point_catalog
  for all using (true) with check (true);`}
            </pre>
          </div>
        </div>
      )}

      <div className="flex flex-wrap items-end gap-3 rounded-xl border border-ces-border bg-ces-card p-4">
        <div className="min-w-[240px] flex-1">
          <label className="label">Search</label>
          <Input
            placeholder="Search pain points or tags…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <div className="min-w-[160px]">
          <label className="label">Theme</label>
          <select
            className="select"
            value={themeFilter}
            onChange={(e) => setThemeFilter(e.target.value)}
          >
            <option value="">All Themes</option>
            {THEMES.map((t) => (
              <option key={t} value={t}>
                {t}
              </option>
            ))}
          </select>
        </div>
      </div>

      <p className="text-sm text-ces-muted">
        {filtered.length} pain point{filtered.length !== 1 ? 's' : ''}
      </p>

      <div className="grid gap-3">
        {filtered.map((item) => (
          <div
            key={item.id}
            className="flex items-start justify-between gap-4 rounded-xl border border-ces-border bg-ces-card p-4"
          >
            <div className="min-w-0 flex-1 space-y-2">
              <p className="text-sm font-medium text-ces-text">{item.text}</p>
              <div className="flex flex-wrap items-center gap-2">
                <Badge variant="industry">{item.theme}</Badge>
                {item.tags.map((tag) => (
                  <Badge key={tag} variant="default">
                    {tag}
                  </Badge>
                ))}
              </div>
            </div>
            <div className="flex shrink-0 gap-2">
              <Button size="sm" variant="secondary" onClick={() => openEdit(item)}>
                <Pencil className="h-3.5 w-3.5" />
              </Button>
              <Button size="sm" variant="danger" onClick={() => handleDelete(item.id)}>
                <Trash2 className="h-3.5 w-3.5" />
              </Button>
            </div>
          </div>
        ))}
        {filtered.length === 0 && !tableMissing && (
          <div className="rounded-xl border border-dashed border-ces-border bg-ces-card p-12 text-center">
            <p className="text-ces-muted">No catalog items yet. Add your first reusable pain point.</p>
          </div>
        )}
      </div>

      <Modal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        title={editing ? 'Edit Pain Point' : 'Add Pain Point'}
        size="md"
        footer={
          <div className="flex justify-end gap-2">
            <Button variant="ghost" onClick={() => setModalOpen(false)}>
              Cancel
            </Button>
            <Button
              variant="primary"
              onClick={handleSave}
              loading={createItem.isPending || updateItem.isPending}
              disabled={!form.text.trim()}
            >
              {editing ? 'Save Changes' : 'Add to Catalog'}
            </Button>
          </div>
        }
      >
        <div className="space-y-4">
          <div>
            <label className="label">Pain Point Text</label>
            <Input
              value={form.text}
              onChange={(e) => setForm((f) => ({ ...f, text: e.target.value }))}
              placeholder="e.g. Legacy systems block modern API-first integrations"
            />
          </div>
          <div>
            <label className="label">Theme</label>
            <select
              className="select"
              value={form.theme}
              onChange={(e) => setForm((f) => ({ ...f, theme: e.target.value }))}
            >
              {THEMES.map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="label">Tags (comma separated)</label>
            <Input
              value={form.tags}
              onChange={(e) => setForm((f) => ({ ...f, tags: e.target.value }))}
              placeholder="e.g. legacy, api, integration"
            />
          </div>
        </div>
      </Modal>
    </div>
  )
}
